### ISSUE TITLE
Open the new Worktree in new Visual Studio Code instance

### ISSUE THREAD

**Issue by rhalaly** [alexiszamanidis/vscode-git-worktrees#10]
First, thank you for this wonderful extension!

I tried to add a new Worktree, but after I added it, the existing VSCode restarted with the new folder. I think it is better to open **a new instance** of VSCode instead.

I use Worktrees for working on several branches to **prevent** switching. But the extension enforces me to switch between worktrees.

Can it open a new instance instead?

**Comment by alexiszamanidis** [comment]
Hi @rhalaly,

Great idea!

I implemented a solution for your needs. 

You can add this property `"vsCodeGitWorktrees.move.openNewVscodeWindow": true` to your vscode settings and will be able to open new vscode instances when you switch or create a worktree.

I hope the implementation suits you!

If you have a better idea, please suggest it.

**Comment by rhalaly** [comment]
@alexiszamanidis Thanks for the ultra fast response! This is an amazing solution!

Can't wait to get that release!

**Comment by alexiszamanidis** [comment]
It has already been published.

Please let me know if everything goes well!

**Comment by rhalaly** [comment]
Works awesome! Thank you for the rapid response! Closing this issue 😄

**Comment by alexiszamanidis** [comment]
You are welcome!

I'm glad you liked it.

Thank you for your contribution!
