### ISSUE TITLE
FR: Change new worktree location

### ISSUE THREAD

**Issue by yrtimiD** [alexiszamanidis/vscode-git-worktrees#11]
From what I understand from the code, addRemoteWorktree will try to put a new worktree in the workspace root path. So, the new workspace folder will essentially be inside a main repo, which feels weird to me.
I usually put different workspaces side by side under same root folder, like this:

```
projects/projX/master    // git repo root
projects/projX/featureA  // worktree for the featureA
```
so, essentially a new worktree folder location is calculated like:
```dirname `git rev-parse --show-toplevel` ``` \+ `${newBranch}`

Any chance to have this configurable in the extension (also for new worktree branches)?

**Comment by alexiszamanidis** [comment]
Hi @yrtimiD,

The main idea is that you have the worktree you are currently working on open in VSCode. The new worktree you want to add will be created one level above.

Example:

Imagine you have opened the featureA worktree in VSCode.

`/projects/repo1/featureA`

If you want to add featureB worktree, it will be created as shown below:

`/projects/repo2/featureB`

But the truth is that if you have opened a folder inside your worktree (e.g. `/projects/repo1/featureA/folder1`), it will create the new worktree inside the featureA folder(`/projects/repo1/featureA/featureB`).

I'm not sure why anyone would do this, but it would be great to use your worktree path calculation to handle these situations.

Thank you for your contribution. I will try to enhance the current implementation as soon as possible.

**Comment by yrtimiD** [comment]
Yes, the location is now as I'd expect it! Thanks for fast fix!
There are other issues I observe now, will open separate issues or PR's if you don't mind

**Comment by alexiszamanidis** [comment]
You are welcome!

Please let me know if you need anything else. 
It's my pleasure to have people contribute to my projects.

Thank you again for your time and contribution!

**Comment by alexiszamanidis** [comment]
Hi @yrtimiD, 

Logging has been added for the commands. 

The main idea is that all commands should be executed by the `executeCommand` function.
This function handles the error message if something goes wrong.
Current format: `command: '${command}'. Error: '${e.message}'`.

Please let me know if this is something you like or have better ideas to improve it.

**Comment by alexiszamanidis** [comment]
When I execute this command:

```
git rev-parse --git-common-dir --path-format=absolute
```

It seems that the `--path-format` has no effect on the output(even with the relative value).
- In the common directory it returns `.git`.
- In a worktree it returns the absolute path.

Does it happen on your system?
Do you believe this is an issue we should handle?

Last but not least, the solution for the path will look something like this.

```
dirname (dirname $(git rev-parse --git-common-dir --path-format=absolute))
```

Is this right?

**Comment by yrtimiD** [comment]
checked in the manual, was surprised to discover that position of path-format is important and it should appear before the flag it expected to affect, so in our case next should always return absolute path (tested in my system):
`git rev-parse --path-format=absolute --git-common-dir`

Regarding `dirname`, if vscode actually executes it in the shell - by using dirname command you'll prevent Windows users from using your extension. I'd recommend doing all filesystem manipulations with node's path library.

**Comment by alexiszamanidis** [comment]
The enhancement has been published!
