### ISSUE TITLE
Incorrect handling of multi-part branches

### ISSUE THREAD

**Issue by yrtimiD** [alexiszamanidis/vscode-git-worktrees#13]
Worktrees for the multi-part branches, like 'projX/bugfix/123' can't be added.

looks like if you do not specify a branch in the `git worktree add <folder> <branch>` command - git assumes the last part of the folder as a branch name, and new worktree become connected to a wrong branch. The `git branch --set-upstream-to...` command should fix this, but something goes wrong.
Anyway, looks like there is an easier solution:
if you'll merge [these commands](https://github.com/alexiszamanidis/vscode-git-worktrees/blob/04930b952138c3c3ec796b4c522974c42870c7c7/src/helpers/gitWorktreeHelpers.ts#L222-L226):
```ts
const worktreeAddCommand = `git worktree add ${newWorktreePath}`;
await executeCommand(worktreeAddCommand);

const connectBranchCommand = `git branch --set-upstream-to=origin/${newBranch} ${newBranch}`;
await executeCommand(connectBranchCommand);
```
to a single one:
```ts
const worktreeAddCommand = `git worktree add ${newWorktreePath} ${newBranch}`;
await executeCommand(worktreeAddCommand);
```
Resulting worktree folder will be created with the proper branch and upstream.

**Comment by alexiszamanidis** [comment]
Hi @yrtimiD,

Good catch!

Thanks for the solution. I tested it and it seems to work.

The fix has been published!

I also changed the default value of vsCodeGitWorktrees.move.openNewVscodeWindow.
I feel it is good not to lose your previous vscode instance(as default behavior). 
You will also be able to see the informational message about the creation of the new worktree.

**Comment by yrtimiD** [comment]
Great, thanks! 
BTW, as a suggestion, on open a new vscode with a new worktree -  can you pass current opened workspace to it?

**Comment by alexiszamanidis** [comment]
Oh, I see. 

So, you have created a workspace with your worktrees and when you create a new worktree you want to add it to the workspace instead of opening a new vscode instance. Am I right?
If I am, I'm assuming that the vscode won't open/reload, but just add the project to the workspace.

How does that sound to you?
I think it would be a great addition to the current implementation.

**Comment by yrtimiD** [comment]
let's move the "open vscode" offtopic to #15

**Comment by yrtimiD** [comment]
tested, works good now, thank you!

**Comment by alexiszamanidis** [comment]
Hi @yrtimiD,

The enhancement has been published!

I would really like to know if this enhancement was what you were looking for.

Please test it when you are free and let me know about your experience.
