### ISSUE TITLE
FR: Open same folder/workspace when switching worktree

### ISSUE THREAD

**Issue by yrtimiD** [alexiszamanidis/vscode-git-worktrees#15]
Monorepo with many projects usually have many workspaces which isolate only relevant folders for specific project.
(can create a demo repo to visualize this)

Imaging next situation:
User is on master with workspace called "ProjectA".
User decides to start working on a new FeatureA for ProjectA, so he'll want to create a new worktree for it, open new vscode in this new worktree folder and open a "ProjectA" workspace in this new worktree.

This is something I'd love to see integrated into this extension.

[moveIntoWorktree](https://github.com/alexiszamanidis/vscode-git-worktrees/blob/df90c33601df004a5d59e55df9458716f6e80971/src/helpers/gitWorktreeHelpers.ts#L26) should check if current vscode instance has open folder or workspace, and reopen same folder/workspace in the new worktree (same or new vscode instance). (will definitely need some absolute-relative-newAbsolute path calculations). I don't know vscode api, so can't point you to specific function.

**Comment by alexiszamanidis** [comment]
Can you please create the demo you mentioned? 
I would also like some base cases to start thinking about what should happen in each scenario. 
Would it be easy for you to create some?

**Comment by yrtimiD** [comment]
Sure, here you go: https://github.com/yrtimiD/stunning-fiesta
If you'll just open a root folder you'll see all the folders in the repo, and in the big monorepo it might be messy:
![image](https://user-images.githubusercontent.com/816805/192353726-242e9fc5-c61f-44f0-aa7a-831bf1096c20.png)
So we create a separate workspaces which narrow explorer to only relevant items. For example, the workspace for "project-a" is located under `project-a/.vscode/project-a.code-workspace` and will look next:
![image](https://user-images.githubusercontent.com/816805/192354337-983b8bea-c262-4686-829f-6db34fb7b16c.png)

Also I created few branches for example:
![image](https://user-images.githubusercontent.com/816805/192354650-355f6f4d-6184-4e2d-9373-89c1840d0440.png)

So, if I originally checkout a repo under `stunning-fiesta/main` folder, then all worktrees maybe created directly under `stunning-fiesta` root folder and exactly represent branches hierarchy:
```
stunning-fiesta
├── main
│   ├── .git
│   │   ├── index
│   │   ├── info
│   │   ├── logs
│   │   ├── objects
│   │   ├── ORIG_HEAD
│   │   ├── packed-refs
│   │   ├── refs
│   │   └── worktrees
│   ├── common
│   │   └── README.md
│   ├── project-a
│   │   ├── README.md
│   │   └── .vscode
│   │       └── project-a.code-workspace
│   ├── project-b
│   │   ├── README.md
│   │   └── .vscode
│   │       └── project-b.code-workspace
│   ├── README.md
│   └── .vscode
│       └── all.code-workspace
├── project-a
│   └── bugfix
│       └── 1
│           ├── common
│           │   └── README.md
│           ├── .git
│           ├── project-a
│           │   ├── README.md
│           │   └── .vscode
│           │       └── project-a.code-workspace
│           ├── project-b
│           │   ├── README.md
│           │   └── .vscode
│           │       └── project-b.code-workspace
│           └── README.md
└── project-b
    └── bugfix
        └── 2
            ├── common
            │   └── README.md
            ├── .git
            ├── project-a
            │   ├── README.md
            │   └── .vscode
            │       └── project-a.code-workspace
            ├── project-b
            │   ├── README.md
            │   └── .vscode
            │       └── project-b.code-workspace
            └── README.md
```
Notice that main .git folder is located at `stunning-fiesta/main/.git` (that's the folder we get with `git rev-parse --git-common-dir`) and can go two levels up to find the root repo folder "stunning-fiesta".

Hope this helps you understand the whole picture

**Comment by yrtimiD** [comment]
now example:
assuming I have a project-a workspace opened from `stunning-fiesta/main/project-a/.vscode/project-a.code-workspace`
and add new or switch to worktree for the `project-a/bugfix/1` branch, I'd like a new vscode to open as 
vscode  
```
stunning-fiesta/project-a/bugfix/1/project-a/.vscode/project-a.code-workspace
\_repo_root__/ \worktree_(branch)/\_______path_to_the_workspace_file_______/
````

**Comment by alexiszamanidis** [comment]
Thanks for the detailed explanation!

I will start investigating how we can add this feature to our extension.

**Comment by alexiszamanidis** [comment]
Hi @yrtimiD,

The enhancement has been published!

I would really like to know if this enhancement was what you were looking for.

Please test it when you are free and let me know about your experience.

**Comment by yrtimiD** [comment]
Thank you again! Just tested on 1.0.20 and the new worktree was opened with the correct workspace!
