### ISSUE TITLE
Error adding worktree

### ISSUE THREAD

**Issue by BrianKmdy** [alexiszamanidis/vscode-git-worktrees#17]
I'm getting an error when I try to add a new worktree.

```
Git Worktrees: Error: Error: command: 'git -C --path-format=absolute.git rev-parse --is-bare-repository'. error: 'Command failed: git -C --path-format=absolute.git rev-parse --is-bare-repository fatal: cannot change to '--path-format=absolute.git': No such file or directory '
```

Any idea what's wrong?

**Comment by alexiszamanidis** [comment]
Hi @BrianKmdy,

Can you please check your git version? If your git is outdated, please upgrade it to latest.

Please let me know if this was the issue.

**Comment by BrianKmdy** [comment]
Using a newer version of git worked for me, thanks! For reference I was having issues with version `2.30.2` and got it to work with `2.37.2`

**Comment by alexiszamanidis** [comment]
You are welcome. 

Thank you for your reference.
