### ISSUE TITLE
Does a tree have to be pushed?

### ISSUE THREAD

**Issue by ericclemmons** [alexiszamanidis/vscode-git-worktrees#25]
When reviewing PRs for an org's repo, I don't have explicit `git push` permissions, only to my fork.

So I can't `add` a worktree because the command fails creating it (and then pushing it)

**Comment by zcfan** [comment]
@alexiszamanidis

**Comment by zcfan** [comment]
@alexiszamanidis 
How about we make auto pull/push a option in extension setting?

**Comment by alexiszamanidis** [comment]
Hi @zcfan,

I truly appreciate your suggestion.
It's an excellent idea that aligns perfectly with enhancing the functionality of our open-source project. 
I'm committed to implementing the "auto pull/push" option at the earliest opportunity.

In regard to this feature, I'd like to gather your insight on whether you envision it being enabled by default or requiring users to manually turn it on. From my perspective, having it enabled by default seems logical. This way, when users attempt their initial push, it could potentially preempt the error scenario you mentioned by ensuring their local repository is up to date with the remote repository. Your thoughts on this aspect would be valuable as we move forward with refining this feature.

Thank you once again for your valuable contribution and engagement with the project. 

Looking forward to your insights!

**Comment by zcfan** [comment]
@alexiszamanidis I prefer not to auto pull/push by default, since it's the default behavior of `git worktree add`. Which means no "surprise" to newcomer.

But previous versions of your extension is auto by default, and it has so many users already!🎉 So keep consistent is also acceptable.

Personally I perfer not to auto pull/push, because the repo I'm working on is messy, remote commits might break my local workspace accidentally.

**Comment by alexiszamanidis** [comment]
@zcfan 
I understand the importance of maintaining consistency with the existing extension's auto-push behavior, especially given its established user base. However, your valid point about the default behavior being off aligns with Git's standard approach. It's crucial to consider both perspectives. In light of this, I'll proceed with the auto push option enabled to assess its impact and gather insights on user experience and workflow.

**Comment by alexiszamanidis** [comment]
Hi @zcfan,

I am glad to inform you that the options have been added.

Please take a moment to check them out and provide valuable feedback on the work.

I apologize for any delay in implementing these changes - I was in a bit of a rush.

Looking forward to hearing your thoughts!

Pull Request: #34
Released Version: 2.2.0 [0bc1c61](https://github.com/alexiszamanidis/vscode-git-worktrees/commit/0bc1c61d176ca191dd2ba113a73ede628e7adf12)

**Comment by zcfan** [comment]
@alexiszamanidis Work like a charm, thank you!

**Comment by alexiszamanidis** [comment]
@zcfan 

Glad you like it!
