### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by assignUser** [alexiszamanidis/vscode-git-worktrees#3]
Due to your use of awk [here](https://github.com/alexiszamanidis/vscode-git-worktrees/blob/0c40d3b46386a21049d6b292d984f149a6a76249/src/helpers/gitHelpers.ts#L135) adding a tree fails on windows. 
One possible solution would be use the git-bash that comes with awk.

Aside from the bug, should the extension even remove branches unasked?

**Comment by assignUser** [comment]
same issue here https://github.com/alexiszamanidis/vscode-git-worktrees/blob/8b838de0341b36fa1bdb1a908742a4e4ac3bf4b5/src/helpers/gitHelpers.ts#L58

**Comment by alexiszamanidis** [comment]
In my opinion, WSL is established on Windows.
Have you tried it with WSL? Do you think this is a solution for Windows or would it be better to move on to what you suggested?

Branches deleted without asking the user are stalled. This means that these branches are deleted remotely, but are available locally.

**Comment by assignUser** [comment]
Well yes it works in wsl but that is linux so I could not use it for windows development. It would be possible to use wsl to solve this via prefixing the linux commands like this `wsl awk`.

Sure I think this is still a choice the user should be aware of and have the possibility of turning off. After all the command is "add a new worktree" not "add a new worktree and clean up branches"

I also want to thank you for the extension as it works quite well (on linux :P)!

**Comment by jonz94** [comment]
Hi Alexis, I just open a PR to add Windows support for this extension.
If you have some free time, please take a look. ☺️

**Comment by alexiszamanidis** [comment]
Hi jonz94, I reviewed your PR and your solution seems neat. I will proceed with the merge and the publish of the improvement.

Thank you both for your time and contribution!
