### ISSUE TITLE
Love it!! Will this restrict using other VSCode git-related extensions

### ISSUE THREAD

**Issue by desmond-dsouza** [alexiszamanidis/vscode-git-worktrees#32]
Sorry for asking this here, please delete if not appropriate. If this will complicate using other VSCode git extensions, any guidance on how to work through those would be helpful. Thanks!

**Comment by alexiszamanidis** [comment]
No problem at all for asking here, and it's completely appropriate to seek guidance. I want to assure you that using this extension shouldn't cause any conflicts or complications with other VSCode git extensions. Based on my experience, no issues have occurred when using this extension alongside others.

However, if you do happen to encounter any conflicts or face difficulties while using other git extensions, I would be more than happy to help you troubleshoot. Please feel free to create an issue at any time, and I'll gladly take a look at it and provide the necessary assistance. 

Glad you love it!

**Comment by alexiszamanidis** [comment]
Hi @desmond-dsouza,

I wanted to check if my previous response resolved your concern. 
Please confirm so I can close the issue.

**Comment by desmond-dsouza** [comment]
Yes, all good. And thanks for the quick reply!
