### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by ahmed-rafiullah** [alexiszamanidis/vscode-git-worktrees#35]
"Error: command: 'git worktree add --track -b hotfix /Users/ahmedrafiullah/Desktop/remotebase/hotfix origin/develop'. error: 'Command failed: git worktree add --track -b hotfix /Users/ahmedrafiullah/Desktop/remotebase/hotfix origin/develop\n" +
  "Preparing worktree (new branch 'hotfix')\n" +
  "fatal: cannot lock ref 'refs/heads/hotfix': 'refs/heads/hotfix/fix-stuff' exists; cannot create 'refs/heads/hotfix'\n" +
  "'"

**Comment by ahmed-rafiullah** [comment]
same branch name is the issue, already had one with the name hotfix before

**Comment by alexiszamanidis** [comment]
Thank you for bringing this to my attention and for your honesty in acknowledging the issue. 
I appreciate your willingness to take responsibility. 
If you have any further questions or need assistance with anything else in the future, please don't hesitate to reach out.
