### ISSUE TITLE
Remove with force

### ISSUE THREAD

**Issue by painhardcore** [alexiszamanidis/vscode-git-worktrees#7]
I'm often feel disappointed ~~in my life~~ in the current worktree and I want to get rid of it quickly.
So it would be great if I can easily delete it with the extension.
Currently, I'm getting this, and I forced to open terminal.
```
Git Worktrees: Error: Command failed: git worktree remove goddamntry
fatal: 'goddamntry' contains modified or untracked files, use --force to delete it
```

**Comment by alexiszamanidis** [comment]
Hi @painhardcore,

This is a great idea, I will adapt it to the current git worktree removal operation.

**Comment by painhardcore** [comment]
@alexiszamanidis great to hear that. Thanks 👍

**Comment by alexiszamanidis** [comment]
Hi @painhardcore,

Force remove has been added to the extension.

I hope the implementation suits you!

**Comment by alexiszamanidis** [comment]
Hi @painhardcore,

Do you like the solution with the Popup?
Or would it be better to add a force remove command?

**Comment by painhardcore** [comment]
@alexiszamanidis I think popup works great. This what I wanted. Thank you. 🥇

**Comment by alexiszamanidis** [comment]
You are welcome!

I'm glad you liked it.

Thank you for your time and contribution!
